# Site settings
# Site settings
title: Drossel/Studio
description: '星好きナントカサークル<br>スマートフォン向け音楽ゲーム「コトノネドライブ」の開発中'
url: 'https://drossel.studio'
baseurl: '/jekyll-uno/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Kokyu Kotone'
  email: info.drossel.studio@gmail.com
  twitter_username: drossel_studio
  facebook_username: 
  github_username:  
  linkedin_username:  

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
